### ISSUE TITLE
IDF website is down

### ISSUE THREAD

**Issue by IuliiaV** [InteractionDesignFoundation/handbook#37]
I see "No input file specified." on the white screen instead of my courses view.
And when i go to the https://www.interaction-design.org/ i see your IxDF Dev handbook.
I would like to study instead of seeing you code ))

**Comment by madssoegaard** [comment]
@IuliiaV Thanks soooooooooooooooooo much for this report ❤️ 

We're back online now 🚀 

One of our deployment scripts had a really bad day and decided to go rogue on us 😆

**Comment by IuliiaV** [comment]
Thank you for your reactivity and goof continuation!
